name: Deploy WordPress to cPanel

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Use secret
        run: |
          echo "The secret is: ${{ secrets.TEST }}"
